C=gcc
CFLAGS=-Wall
all: dcooke_analyzer
dcooke_analyzer: mains.o

	$(CC)	$(CFLAGS) -o dcooke_analyzer mains.o

cdooke_analyzer: mains.c

	$(CC)	$(CFLAGS) -c mains.c

clean:

	rm -f *-o dcooke_analyzer
