C=gcc
CFLAGS=-Wall
all: dcooke_parser
dcooke_parser: mains.o

	$(CC)	$(CFLAGS) -o dcooke_parser mains.o

cdooke_parser: mains.c

	$(CC)	$(CFLAGS) -c mains.c

clean:

	rm -f *-o dcooke_parser
